// Shared catalog resolver. Resolves a catalog slug to a concrete launch
// shape (command + args + required env keys) from the SAME static catalog
// the yaw.sh website and the Yaw Terminal app read:
//
//     https://yaw.sh/data/mcp-catalog.json
//
// Why one source: the website catalog page emits "Add to Yaw MCP" buttons
// carrying a `slug`, and both the Yaw Terminal app (yaw-install-handler.ts
// resolveSlug) and this CLI must accept the EXACT same slug set, or a button
// that works in the app silently fails in the CLI fallback. Keeping all three
// pointed at one static file is what guarantees slug parity.
//
// Both `yaw-mcp add <slug>` and `yaw-mcp try <slug>` resolve through here, so
// a catalog shape change is fixed in one place.

const DEFAULT_CATALOG_URL = "https://yaw.sh/data/mcp-catalog.json";
const FETCH_TIMEOUT_MS = 10_000;
const ENV_KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** A single required-env descriptor as the catalog stores it. */
export interface CatalogRequiredEnv {
  key: string;
  label?: string;
  placeholder?: string;
  docsUrl?: string;
}

/** A raw catalog server entry (only the fields this resolver reads). */
export interface CatalogServer {
  slug: string;
  name?: string;
  description?: string;
  install?: { command?: string; runtime?: string; url?: string; type?: string };
  requiredEnv?: CatalogRequiredEnv[];
  repo?: string;
  homepage?: string;
}

/** The resolved launch shape `add`/`try` consume. command + args are split
 *  from the catalog's single `install.command` launch line via tokenizeCommand. */
export interface ResolvedCatalogServer {
  slug: string;
  name: string;
  command: string;
  args: string[];
  /** Names (not values) of env vars the server needs. */
  requiredEnvKeys: string[];
  description?: string;
  source?: string;
  docUrl?: string;
}

export type FetchCatalog = (url: string) => Promise<CatalogServer[]>;

/**
 * Quote-aware split of a catalog `install.command` launch line into
 * command + argv. The catalog stores the whole line as one string
 * (e.g. `npx -y @yawlabs/aws-mcp`, or `docker run -i --rm -e FOO ghcr.io/...`),
 * but a bundles.json entry needs command and args separate. Mirror of the
 * app's tokenizeCommand (yaw-install-handler.ts) and the website's
 * (catalog/index.html), so all three produce identical splits.
 */
export function tokenizeCommand(cmd: string): string[] {
  const out: string[] = [];
  let cur = "";
  let has = false;
  let quote: '"' | "'" | null = null;
  for (const ch of cmd) {
    if (quote) {
      if (ch === quote) quote = null;
      else cur += ch;
      has = true;
    } else if (ch === '"' || ch === "'") {
      quote = ch;
      has = true;
    } else if (ch === " " || ch === "\t" || ch === "\n" || ch === "\r") {
      if (has) {
        out.push(cur);
        cur = "";
        has = false;
      }
    } else {
      cur += ch;
      has = true;
    }
  }
  if (quote !== null) {
    throw new Error(`Unbalanced quote in command: ${cmd}`);
  }
  if (has) out.push(cur);
  return out;
}

/** Age past which the catalog's own `generated_at` stamp earns a staleness
 *  note. The catalog is a static file regenerated by the yaw.sh site build,
 *  so a gap of weeks is normal cadence -- but a quarter-old snapshot handing
 *  out install lines deserves a heads-up: package names, launch commands and
 *  required env drift on that timescale. Advisory only; a stale catalog
 *  still resolves. */
export const CATALOG_STALE_AFTER_DAYS = 90;

/** Surface the catalog's `generated_at` stamp when it is old enough to
 *  matter. The parser used to read only `body.servers` and drop the one
 *  field that distinguishes a frozen catalog from a fresh one -- `add` and
 *  `try` would keep handing out an old snapshot's install lines forever with
 *  nothing anywhere able to say the source went stale. A missing, non-string
 *  or unparsable stamp stays silent (the field is optional), as does a
 *  future-dated one (clock skew is not staleness). Warns on stderr so the
 *  note never contaminates machine-read stdout, and never throws. */
function warnIfCatalogStale(body: unknown, opts: CatalogFetchDeps): void {
  const stamp = (body as { generated_at?: unknown } | null)?.generated_at;
  if (typeof stamp !== "string") return;
  const generated = Date.parse(stamp);
  if (Number.isNaN(generated)) return;
  const ageDays = Math.floor(((opts.now?.() ?? Date.now()) - generated) / 86_400_000);
  if (ageDays < CATALOG_STALE_AFTER_DAYS) return;
  const warn = opts.warn ?? ((line: string) => process.stderr.write(`${line}\n`));
  warn(
    `yaw-mcp: note: the Yaw MCP catalog was generated ${stamp.slice(0, 10)} (${ageDays} days ago); its entries may be out of date.`,
  );
}

/** Test seams for defaultFetchCatalog's staleness note. Optional second
 *  parameter so the function stays assignable to FetchCatalog. */
export interface CatalogFetchDeps {
  /** Sink for the staleness note. Defaults to process.stderr. */
  warn?: (line: string) => void;
  /** Clock for the age computation. Defaults to Date.now. */
  now?: () => number;
}

/** Fetch + shape-validate the catalog. Bounded by FETCH_TIMEOUT_MS. Throws a
 *  friendly Error on network / parse / shape failure. Injectable for tests. */
export async function defaultFetchCatalog(
  url: string = DEFAULT_CATALOG_URL,
  deps: CatalogFetchDeps = {},
): Promise<CatalogServer[]> {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), FETCH_TIMEOUT_MS);
  let body: unknown;
  try {
    const res = await fetch(url, { signal: ac.signal, headers: { accept: "application/json" } });
    if (!res.ok) {
      throw new Error(`the Yaw MCP catalog at ${url} returned HTTP ${res.status}.`);
    }
    // A 200 whose body isn't JSON is the captive-portal / corporate-proxy
    // shape: the request "succeeded" and returned an HTML login page. Left
    // unwrapped, the raw SyntaxError reaches the user as `yaw-mcp add:
    // Unexpected token '<', "<!DOCTYPE "... is not valid JSON` -- naming
    // neither the catalog nor the URL that produced it. Wrap it here so every
    // failure mode of this function carries the same "catalog at <url>" prefix
    // its docstring promises. An abort that lands while the BODY is streaming
    // also rejects here; rethrow that untouched so the outer catch keeps
    // reporting it as the timeout it is.
    try {
      body = await res.json();
    } catch (parseErr) {
      if (parseErr instanceof Error && parseErr.name === "AbortError") throw parseErr;
      const msg = parseErr instanceof Error ? parseErr.message : String(parseErr);
      throw new Error(`the Yaw MCP catalog at ${url} did not return valid JSON (${msg}).`);
    }
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") {
      throw new Error(`timed out fetching the Yaw MCP catalog at ${url}.`);
    }
    // Anything thrown ABOVE already carries the "catalog at <url>" prefix, so
    // rethrow those untouched -- the url test is what tells them apart.
    if (err instanceof Error && err.message.includes(url)) throw err;
    // Everything else is a TRANSPORT failure raised by fetch itself: offline,
    // DNS, connection refused, TLS, a proxy that drops the connection. undici
    // reports every one of them as a bare `TypeError: fetch failed`, which
    // names neither the catalog nor the URL -- so `yaw-mcp add <slug>` on a
    // laptop with no network printed exactly "yaw-mcp add: fetch failed".
    // That is the most common failure this function has, and it was the one
    // mode the wrapping above did not cover. The real reason lives on
    // `cause` (ECONNREFUSED, ENOTFOUND, ...); surface it.
    const cause = err instanceof Error && err.cause instanceof Error ? err.cause.message : null;
    const detail = cause ?? (err instanceof Error ? err.message : String(err));
    throw new Error(`could not reach the Yaw MCP catalog at ${url} (${detail}). Check your network, then retry.`);
  } finally {
    clearTimeout(timer);
  }
  const servers = (body as { servers?: unknown } | null)?.servers;
  if (!Array.isArray(servers)) {
    throw new Error(`the Yaw MCP catalog at ${url} was not in the expected shape.`);
  }
  warnIfCatalogStale(body, deps);
  return servers.filter(
    (s): s is CatalogServer => typeof s === "object" && s !== null && typeof (s as CatalogServer).slug === "string",
  );
}

/**
 * Resolve a catalog slug to a concrete launch shape. Refuses remote/HTTP
 * servers (they have no stdio spawn command) the same way the app's
 * resolveSlug does. Throws a friendly Error on miss / remote / empty command.
 */
export async function resolveCatalogSlug(
  slug: string,
  opts: { catalogUrl?: string; fetchCatalog?: FetchCatalog } = {},
): Promise<ResolvedCatalogServer> {
  const url = opts.catalogUrl ?? DEFAULT_CATALOG_URL;
  const fetchCatalog = opts.fetchCatalog ?? defaultFetchCatalog;
  const servers = await fetchCatalog(url);
  const entry = servers.find((s) => s.slug === slug);
  if (!entry) {
    throw new Error(
      `no server with slug "${slug}" in the Yaw MCP catalog. Browse https://yaw.sh/mcp/catalog/ for the list.`,
    );
  }

  const install = entry.install ?? {};
  const runtime = typeof install.runtime === "string" ? install.runtime.toLowerCase() : "";
  // A remote/HTTP server has no stdio spawn command; refuse rather than
  // tokenize a URL into a broken entry. Matches the app's resolveSlug.
  if (install.url || install.type === "remote" || /^(remote|https?|sse|url)$/.test(runtime)) {
    throw new Error(
      `"${slug}" is a remote (HTTP) server, which has no stdio command to spawn. Add it by hand to ~/.yaw-mcp/bundles.json with "type": "remote" and its "url".`,
    );
  }
  const cmdStr = typeof install.command === "string" ? install.command.trim() : "";
  if (!cmdStr) {
    throw new Error(`catalog entry "${slug}" has no install command.`);
  }
  const tokens = tokenizeCommand(cmdStr);
  if (tokens.length === 0) {
    throw new Error(`catalog entry "${slug}" install command was empty.`);
  }
  const [command, ...args] = tokens;

  const requiredEnvKeys = Array.isArray(entry.requiredEnv)
    ? entry.requiredEnv
        .map((e) => (e && typeof e === "object" ? e.key : undefined))
        .filter((k): k is string => typeof k === "string" && ENV_KEY_RE.test(k))
    : [];

  const source =
    typeof entry.repo === "string" ? entry.repo : typeof entry.homepage === "string" ? entry.homepage : undefined;
  return {
    slug,
    name: typeof entry.name === "string" && entry.name.trim() ? entry.name.trim() : slug,
    command,
    args,
    requiredEnvKeys,
    description: typeof entry.description === "string" ? entry.description : undefined,
    source,
    docUrl: source,
  };
}

export { DEFAULT_CATALOG_URL };
